version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  app:
    image: dansiwiec/todo-deploy:latest
    ports:
     - 8080:8080
    depends_on:
    - db
    environment:
      DB: mongodb://db
      PORT: 8080